---
- name: Create TLS certificate
  gather_facts: true
  hosts: all
  vars:
    user: benmusashi
    group: root
    terraform_key_path: /home/benmusashi/.pki/libvirt
    terraform_cert_path: /home/benmusashi/.pki/libvirt
    terraform_key_file: clientkey.pem
    terraform_cert_file: clientcert.pem
  become: true
  become_user: root
  roles:
    - role: pki-create-cert
      _ca_name: 'honbu-pki-test.jinteki.lan' 
      _client_group_name: terraform_servers
      _key_path_var: terraform_key_path
      _key_file_var: terraform_key_file
      _cert_path_var: terraform_cert_path
      _cert_file_var: terraform_cert_file
      _owner_user_var: user
      _owner_group_var: group
      _csr_template_name: TLS_terraform
      _ca_template_name: TLS_client
