---
- name: update all packages
  gather_facts: true
  hosts: all
  become: true
  become_user: root
  roles:
    - { role: reflector, when: "('alias_servers' not in  group_names) and (ansible_distribution == 'Archlinux')" }
