---
- name: update all packages
  gather_facts: true
  hosts: all
  become: true
  become_user: root
  roles:
    - { role: trust-certs, pki_group: 'pki_test_servers', _trust_certs_dir: "~/test-certs" }
